# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "kamui-terraform-state"
    dynamodb_table = "kamui-terraform-state-lock"
    encrypt        = true
    key            = "terragrunt/development/terraform.tfstate"
    region         = "eu-central-1"
  }
}
